variable "name" {}
variable "location" {}
variable "resource_group_name" {}
variable "dns_prefix" {}
variable "default_node_pool_name" {}
variable "default_node_pool_node_count" {}
variable "default_node_pool_vm_size" {}
variable "identity_type" {}
variable "network_profile_network_policy" {}
variable "oms_agent_log_analytics_workspace_id" {}
variable "automatic_upgrade_channel" {}
variable "api_server_access_profile_authorized_ip_ranges" {}
variable "max_pods" {}
variable "bool_true" {}
variable "disk_encryption_set_id" {}
variable "aks_sku" {}