trigger:
  branches:
    include:
      - develop
  paths:
    include:
      - "app/**"

pr:
  branches:
    include:
      - develop
  paths:
    include:
      - "app/**"

pool:
  vmImage: 'ubuntu-latest'

variables:
  ACR_NAME: reactappacr47     # ✅ FIXED: no self-reference
  IMAGE_NAME: noteapp

stages:
  - stage: BuildAndPush
    displayName: 'Build and Push Docker Image to ACR'
    jobs:
      - job: build_and_push
        displayName: 'Build and Push Docker Image'
        steps:

          - checkout: self
            displayName: 'Checkout Code'

          - task: NodeTool@0
            displayName: 'Set up Node.js'
            inputs:
              versionSpec: '18.x'

          - script: |
              cd app
              npm ci
              npm run build
            displayName: 'Install and Build React App'

          - task: AzureCLI@2
            displayName: 'Azure Login'
            inputs:
              azureSubscription: AzureDevOpsSubscription
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Logged into Azure"

          - task: AzureCLI@2
            displayName: 'Login to ACR'
            inputs:
              azureSubscription: AzureDevOpsSubscription
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az acr login --name $(ACR_NAME)

          - script: |
              docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId) ./app
              docker tag $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId) $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest
            displayName: 'Build Docker Image'

          - script: |
              docker run --rm aquasecurity/trivy:latest image --exit-code 1 --severity CRITICAL,HIGH $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId)
            displayName: 'Trivy Image Scan'
            continueOnError: true

          - script: |
              docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId)
              docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest
            displayName: 'Push Docker Image to ACR'
