trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: AzureLogin
  displayName: 'Azure Login Stage'
  jobs:
  - job: LoginJob
    displayName: 'Run az login'
    steps:
    - task: AzureCLI@2
      displayName: 'Azure CLI Login'
      inputs:
        azureSubscription: 'AzureDevOpsSubscription'  # 🔑 Replace with your service connection name
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Logging in to Azure..."
          az account show
