trigger:
  branches:
    include:
      - develop

pr: none

pool:
  vmImage: ubuntu-latest

jobs:
- job: terraform_plan
  displayName: Terraform Plan
  steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: 'Azure Login'
      inputs:
        azureSubscription: '$(AZURE_SERVICE_CONNECTION)'  # Configure service connection in Azure DevOps
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Logged in to Azure"

    - script: terraform init
      displayName: 'Terraform Init'
      workingDirectory: infra

    - script: terraform validate
      displayName: 'Terraform Validate'
      workingDirectory: infra

    - script: terraform plan -out=tfplan
      displayName: 'Terraform Plan'
      workingDirectory: infra
