trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: AzureLoginTerraformPlan
  displayName: 'Azure Login + Terraform Plan'
  jobs:
  - job: LoginInstallPlanJob
    displayName: 'Azure Login + Install Terraform + Plan'
    steps:
    # -----------------------
    # Step 1: Azure Login
    # -----------------------
    - task: AzureCLI@2
      displayName: 'Azure CLI Login'
      inputs:
        azureSubscription: 'AzureDevOpsSubscription'  # Replace with your service connection name
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "✅ Successfully logged in with service connection."
          az account show --output table

    # -----------------------
    # Step 2: Install Terraform
    # -----------------------
    - task: Bash@3
      displayName: 'Install Terraform'
      inputs:
        targetType: 'inline'
        script: |
          echo "⬇️ Installing Terraform..."
          sudo apt-get update -y
          sudo apt-get install -y wget unzip
          TERRAFORM_VERSION="1.9.8"  # 🔧 Change version if needed
          wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

    # -----------------------
    # Step 3: Terraform Init & Plan in infra/ folder
    # -----------------------
    - task: Bash@3
      displayName: 'Terraform Init & Plan (infra/)'
      inputs:
        targetType: 'inline'
        script: |
          echo "🚀 Running Terraform Init & Plan in infra/..."
          cd $(System.DefaultWorkingDirectory)/infra
          terraform init -input=false
          terraform plan -input=false -out=tfplan
