trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # These will be set automatically by AzureCLI@2
  ARM_CLIENT_ID: ''
  ARM_CLIENT_SECRET: ''
  ARM_SUBSCRIPTION_ID: ''
  ARM_TENANT_ID: ''

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - checkout: self

    # Install Terraform (Task handles installation)
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    # ✅ Login to Azure using Service Connection and export ARM_* vars
    - task: AzureCLI@2
      displayName: 'Azure Login and Set Terraform Env Vars'
      inputs:
        azureSubscription: 'AzureDevOpsSubscription' # <-- Replace with your Service Connection name
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Setting Terraform environment variables..."
          echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
          echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$servicePrincipalKey"
          echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
          echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscriptionId"

    # Terraform Init and Plan with SPN auth
    - script: |
        terraform --version
        terraform init
        terraform plan -out=tfplan
      displayName: 'Terraform Init and Plan'
      workingDirectory: infra
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
