trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: AzureLoginTerraformPlan
  displayName: 'Azure Login + Terraform Plan'
  jobs:
  - job: LoginInstallPlanJob
    displayName: 'Single Step: Login + Install + Plan'
    steps:
    - task: AzureCLI@2
      displayName: 'Azure Login + Terraform Install + Plan'
      inputs:
        azureSubscription: 'AzureDevOpsSubscription'  # Replace with your service connection name
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "✅ Logging in to Azure with service connection..."
          az account show --output table

          echo "⬇️ Installing Terraform..."
          sudo apt-get update -y
          sudo apt-get install -y wget unzip
          TERRAFORM_VERSION="1.9.8"
          wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

          echo "🚀 Running Terraform Init & Plan in infra/..."
          cd $(System.DefaultWorkingDirectory)/infra
          terraform init -input=false
          terraform plan -input=false -out=tfplan
