trigger:
  branches:
    include:
      - develop

pool:
  vmImage: ubuntu-latest

jobs:
- job: terraform_plan
  displayName: Terraform Plan
  steps:
    - checkout: self

    # Install Terraform
    - script: |
        sudo apt-get update -y
        sudo apt-get install -y wget unzip jq
        wget https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip
        unzip terraform_1.5.6_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform --version
      displayName: 'Install Terraform CLI'

    # ✅ Export ARM_* env vars from Service Connection
    - task: AzureCLI@2
      displayName: 'Set Terraform Azure Auth Environment Variables'
      inputs:
        azureSubscription: 'AzureDevOpsSubscription'  # Name of your service connection
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Setting environment variables for Terraform"
          echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
          echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$servicePrincipalKey"
          echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
          echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscriptionId"

    - script: terraform init
      displayName: 'Terraform Init'
      workingDirectory: infra
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)

    - script: terraform validate
      displayName: 'Terraform Validate'
      workingDirectory: infra
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)

    - script: terraform plan -out=tfplan
      displayName: 'Terraform Plan'
      workingDirectory: infra
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
