trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - checkout: self

    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    - task: AzureCLI@2
      displayName: 'Azure Login and Set Terraform Env Vars'
      inputs:
        azureSubscription: 'AzureDevOpsSubscription'  # Replace with your service connection name
        scriptType: bash
        scriptLocation: inlineScript
        addSpnToEnvironment: true   # ✅ Important - exposes SPN details as env vars
        inlineScript: |
          echo "Setting Terraform environment variables..."
          echo "##vso[task.setvariable variable=ARM_CLIENT_ID;issecret=true]$servicePrincipalId"
          echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;issecret=true]$servicePrincipalKey"
          echo "##vso[task.setvariable variable=ARM_TENANT_ID;issecret=true]$tenantId"
          echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID;issecret=true]$subscriptionId"

    - script: |
        echo "Terraform Init & Plan"
        terraform --version
        terraform init
        terraform plan -out=tfplan
      displayName: 'Terraform Init and Plan'
      workingDirectory: infra
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
