pool:
  vmImage: ubuntu-latest

variables:
  resourcegroup: terraform-state
  accountname: tfstate0911
  containername: tfstate
  key: noteapp.terraform.tfstate

stages:
  - stage: tfdestroy
    jobs:
      - job: destroy
        continueOnError: false
        steps:
          - task: TerraformInstaller@1
            displayName: install
            inputs:
              terraformVersion: latest
          - task: TerraformTaskV4@4
            displayName: init
            inputs:
              workingDirectory: infra
              provider: azurerm
              command: init
              backendServiceArm: AzureDevOpsSubscription
              backendAzureRmResourceGroupName: $(resourcegroup)
              backendAzureRmStorageAccountName: $(accountname)
              backendAzureRmContainerName: $(containername)
              backendAzureRmKey: $(key)
          - task: TerraformTaskV4@4
            displayName: destroy
            inputs:
              workingDirectory: infra
              provider: azurerm
              command: destroy
              environmentServiceNameAzureRM: AzureDevOpsSubscription