trigger:
  branches:
    include:
      - develop
  paths:
    include:
      - infra/*

pr: none   # Don't auto-run on PRs (plan runs only on develop changes)

stages:
- stage: TerraformPlan
  displayName: "Terraform Plan Stage"
  jobs:
  - job: terraform_plan
    displayName: "Terraform Plan"
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: Checkout@2
      displayName: "Checkout repository"

    - task: UseTerraform@0
      displayName: "Setup Terraform"
      inputs:
        terraformVersion: '1.5.6'

    - task: AzureCLI@2
      displayName: "Azure Login"
      inputs:
        azureSubscription: "YOUR-AZURE-SERVICE-CONN"  # Name of service connection
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Logged in to Azure successfully."

    - script: |
        echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$(ARM_CLIENT_ID)"
        echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$(ARM_CLIENT_SECRET)"
        echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(ARM_SUBSCRIPTION_ID)"
        echo "##vso[task.setvariable variable=ARM_TENANT_ID]$(ARM_TENANT_ID)"
      displayName: "Set Terraform Environment Variables"

    - script: terraform init
      workingDirectory: infra
      displayName: "Terraform Init"

    - script: terraform validate
      workingDirectory: infra
      displayName: "Terraform Validate"

    # Optional Checkov scan
    - script: |
        pip install checkov
        checkov -d infra --quiet --framework terraform
      displayName: "Run Checkov Scan"

    - script: terraform plan -out=tfplan
      workingDirectory: infra
      displayName: "Terraform Plan"

    # Note: PR creation in Azure DevOps is usually manual or via REST API
    # Example (optional) PR creation step using ADO REST API
    # - script: |
    #     echo "Creating PR via Azure DevOps REST API"
    #     curl -u :$(System.AccessToken) \
    #       -H "Content-Type: application/json" \
    #       -X POST \
    #       -d '{
    #             "sourceRefName": "refs/heads/develop",
    #             "targetRefName": "refs/heads/main",
    #             "title": "Merge develop into main",
    #             "description": "Created by Azure DevOps pipeline"
    #           }' \
    #       https://dev.azure.com/<ORG>/<PROJECT>/_apis/git/repositories/<REPO>/pullrequests?api-version=6.0
    #   env:
    #     System.AccessToken: $(System.AccessToken)
    #   displayName: "Create Pull Request"
