trigger:
  branches:
    include:
      - develop
  paths:
    include:
      - infra/*
pool:
  vmImage: ubuntu-latest
variables:
  resourcegroup: terraform-state
  accountname: tfstate0911
  containername: tfstate
  key: noteapp.terraform.tfstate
stages:
  - stage: tfplan
    jobs:
      - job: plan
        continueOnError: false
        steps:
          - task: TerraformInstaller@1
            displayName: install
            inputs:
              terraformVersion: latest
          - task: TerraformTaskV4@4
            displayName: init
            inputs:
              workingDirectory: infra
              provider: azurerm
              command: init
              backendServiceArm: AzureDevOpsSubscription
              backendAzureRmResourceGroupName: $(resourcegroup)
              backendAzureRmStorageAccountName: $(accountname)
              backendAzureRmContainerName: $(containername)
              backendAzureRmKey: $(key)
          - task: TerraformTaskV4@4
            displayName: validate
            inputs:
              workingDirectory: infra
              provider: azurerm
              command: validate
          - task: TerraformTaskV4@4
            displayName: plan
            inputs:
              workingDirectory: infra
              provider: azurerm
              command: plan
              environmentServiceNameAzureRM: AzureDevOpsSubscription
          - powershell: |
              $user = ""
              $token = "$(System.AccessToken)"
              $branchTarget = "refs/heads/main"
              $branchSource = "$(Build.SourceBranch)"
              $branchTragetPath = $branchTarget -replace "refs/heads/", ""
              $teamProject = "$(System.TeamProject)"
              $repoName = "$(Build.Repository.Name)"
              $orgUrl = "$(System.CollectionUri)"

              $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $user,$token)))

              $uriBranchStatus = "$orgUrl/$teamProject/_apis/git/repositories/$repoName/stats/branches?name=$branchTragetPath&api-version=5.1"
              $uriCheckActivePR = "$orgUrl/$teamProject/_apis/git/repositories/$repoName/pullrequests?searchCriteria.targetRefName=$branchTarget&searchCriteria.sourceRefName=$branchSource&api-version=5.1"
              $uriCreatePR = "$orgUrl/$teamProject/_apis/git/repositories/$repoName/pullrequests?api-version=5.1"

              # Check the status of the branch
              $resultStatus = Invoke-RestMethod -Uri $uriBranchStatus -Method Get -ContentType "application/json" -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)}

              if ($resultStatus.behindCount -eq 0) {
                  Write-Host "Current branch contains last changes from master"
                  Return
              }

              # Check if there is an active PR already
              $resultActivePR = Invoke-RestMethod -Uri $uriCheckActivePR -Method Get -ContentType "application/json" -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)}

              if ($resultActivePR.count -gt 0) {
                  Write-Host "PR exists already"
                  Return
              }

              # Create a new PR if none exists
              $bodyCreatePR = "{sourceRefName:'$branchSource',targetRefName:'$branchTarget',title:'Sync changes from $branchSource'}"
              $result = Invoke-RestMethod -Uri $uriCreatePR -Method Post -ContentType "application/json" -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)} -Body $bodyCreatePR

              Write-Host "Created PR" $result.pullRequestId
            displayName: 'Check and Create PR If Plan Is OK'
            condition: succeeded()  # Ensures this script runs only if the plan step is successful
