trigger:
  branches:
    include:
      - develop

pr: none

pool:
  vmImage: ubuntu-latest

jobs:
- job: terraform_plan
  displayName: Terraform Plan
  steps:
    - checkout: self

    # Install Terraform
    - script: |
        sudo apt-get update -y
        sudo apt-get install -y wget unzip
        wget https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip
        unzip terraform_1.5.6_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform --version
      displayName: 'Install Terraform CLI'

    # Azure Login using Service Connection
    - task: AzureCLI@2
      displayName: 'Azure Login'
      inputs:
        azureSubscription: 'AzureDevOpsSubscription' # Configure in Project Settings -> Service Connections
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "✅ Logged in to Azure"

    - script: terraform init
      displayName: 'Terraform Init'
      workingDirectory: infra

    - script: terraform validate
      displayName: 'Terraform Validate'
      workingDirectory: infra

    - script: terraform plan -out=tfplan
      displayName: 'Terraform Plan'
      workingDirectory: infra
