trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: TerraformPlan
  displayName: 'Terraform Plan Stage'
  jobs:
  - job: InstallAndPlan
    displayName: 'Install Terraform + Plan'
    steps:
    - task: Bash@3
      displayName: 'Install Terraform + Run Plan'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)       # Store these in Azure DevOps Pipeline variables
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
      inputs:
        targetType: 'inline'
        script: |
          echo "⬇️ Installing Terraform..."
          sudo apt-get update -y
          sudo apt-get install -y wget unzip
          TERRAFORM_VERSION="1.9.8"
          wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

          echo "🚀 Running Terraform Init & Plan in infra/..."
          cd $(System.DefaultWorkingDirectory)/infra
          terraform init -input=false
          terraform plan -input=false -out=tfplan
