trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

stages:
# -----------------------
# Stage 1: Azure Login
# -----------------------
- stage: AzureLogin
  displayName: 'Azure Login Stage'
  jobs:
  - job: LoginJob
    displayName: 'Run az login'
    steps:
    - task: AzureCLI@2
      displayName: 'Azure CLI Login'
      inputs:
        azureSubscription: 'AzureDevOpsSubscription'  # Replace with your service connection name
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "✅ Successfully logged in with service connection."
          az account show --output table

# -----------------------
# Stage 2: Install Terraform
# -----------------------
- stage: InstallTerraform
  displayName: 'Install Terraform Stage'
  dependsOn: AzureLogin
  jobs:
  - job: TerraformInstallJob
    displayName: 'Install Terraform'
    steps:
    - task: Bash@3
      displayName: 'Install Terraform'
      inputs:
        targetType: 'inline'
        script: |
          echo "⬇️ Installing Terraform..."
          sudo apt-get update -y
          sudo apt-get install -y wget unzip
          TERRAFORM_VERSION="1.9.8"  # 🔧 Change version if needed
          wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform -version
